source 'https://rubygems.org'

ruby '2.6.5'

# Please keep the gems (as well as within a group) sorted
# in alphabetical order.

gem 'acts-as-taggable-on', '~> 3.4'
gem 'aws-sdk', '~> 2.6'
gem 'barometer', '>= 0.9.7'
gem 'bootstrap-datepicker-rails', '>= 1.8.0.1'
gem 'bootstrap-generators', '~> 3.3.4'
gem 'bootstrap-kaminari-views', '>= 0.0.5'
gem 'bourbon', '~> 4.1.1'
gem 'cancancan', '~> 1.10'
gem 'coffee-rails', '~> 4.0.1'
gem 'database_cleaner'
gem 'devise', '>= 4.7.1'
gem 'devise-bootstrap-views'
gem 'email_validator'
gem 'factory_bot_rails', '>= 5.1.1'
gem 'figaro'
gem 'font-awesome-sass', '~> 4.2.0'
gem 'foreman'
gem 'friendly_id'
gem 'gaffe', '>= 1.2.0'
gem 'gon', '>= 6.2.1'
gem 'habtm_generator'
gem 'haml'
gem 'handlebars'
gem 'htmlentities'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails', '>= 4.3.5'
gem 'jquery-slick-rails', '>= 1.9.0'
gem 'js-routes', '>= 1.4.9'
gem 'kaminari', '>= 1.1.1'
gem 'less-rails', '~> 2.7.1'
gem 'message_bus'
gem 'mysql2'
gem 'neat', '~> 1.7.1'
gem 'nokogiri', '>= 1.10.8'
gem 'paperclip', '~> 5.2'
gem 'paranoia'
gem 'pg', '~> 0.15'
gem 'puma'
gem 'rake', '< 11.0'
gem 'rack-attack'
gem 'rack-mini-profiler'
gem 'rails', '4.2.11'
gem 'react-rails', '~> 2.3.1'
gem 'recap', '~> 1.0.0'
gem 'redis-rails', '~> 4', '>= 4.0.0'
gem 'remotipart', '~> 1.2'
gem 'rmagick'
gem 'sass-rails', '~> 5.0.7'
gem 'searchkick'
gem 'sitemap_generator'
gem 'therubyracer'
gem 'twitter-bootstrap-rails', '>= 3.2.2'
gem 'uglifier', '>= 1.3.0'
gem 'weather-icons-rails', '>= 0.1.1'
gem 'whenever'

# Following are the rails-assets.org gems
gem 'rails-assets-axios', source: 'https://rails-assets.org'
gem 'rails-assets-bootstrap-tagsinput', source: 'https://rails-assets.org'
gem 'rails-assets-jquery-timeago', source: 'https://rails-assets.org'
gem 'rails-assets-jquery-typeahead', source: 'https://rails-assets.org'
gem 'rails-assets-jquery.appear.js', source: 'https://rails-assets.org'
gem 'rails-assets-jquery.dotdotdot', '~> 3.2.2', source: 'https://rails-assets.org'
gem 'rails-assets-jsdiff', source: 'https://rails-assets.org'
gem 'rails-assets-typeahead.js', source: 'https://rails-assets.org'
gem 'rails-assets-underscore', source: 'https://rails-assets.org'

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

group :development, :test do
  gem 'capybara', '>= 3.29.0'
  gem 'guard-rspec'
  gem 'launchy'
  gem 'poltergeist', '>= 1.18.1'
  gem 'pry'
  gem 'rspec-rails', '>= 3.9.0'
  gem 'spring'
  gem 'terminal-notifier-guard'
end

group :production do
  gem 'rails_12factor'
end
