source 'https://rubygems.org'

ruby '2.6.5'

# Please keep the gems (as well as within a group) sorted
# in alphabetical order.

gem 'acts-as-taggable-on', '~> 3.4'
gem 'aws-sdk', '~> 1.66'
gem 'barometer'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap-generators', '~> 3.3.1'
gem 'bootstrap-kaminari-views'
gem 'bourbon', '~> 4.1.1'
gem 'cancancan', '~> 1.10'
gem 'coffee-rails', '~> 4.0.0'
gem 'database_cleaner'
gem 'devise'
gem 'devise-bootstrap-views'
gem 'email_validator'
gem 'factory_girl_rails'
gem 'figaro'
gem 'font-awesome-sass', '~> 4.2.0'
gem 'foreman'
gem 'friendly_id'
gem 'gaffe'
gem 'gon'
gem 'habtm_generator'
gem 'haml'
gem 'handlebars'
gem 'htmlentities'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-slick-rails'
gem 'js-routes'
gem 'kaminari'
gem 'less-rails', '~> 2.7.0'
gem 'message_bus'
gem 'mysql2'
gem 'neat', '~> 1.7.1'
gem 'nokogiri'
gem 'paperclip', '~> 4.2'
gem 'paranoia'
gem 'pg'
gem 'puma'
gem 'rake', '< 11.0'
gem 'rack-attack'
gem 'rack-mini-profiler'
gem 'rails', '4.1.8'
gem 'react-rails'
gem 'recap', '~> 1.0.0'
gem 'redis-rails', '~> 4'
gem 'remotipart', '~> 1.2'
gem 'rmagick'
gem 'sass-rails', '~> 5.0.1'
gem 'searchkick'
gem 'sitemap_generator'
gem 'therubyracer'
gem 'twitter-bootstrap-rails'
gem 'uglifier', '>= 1.3.0'
gem 'weather-icons-rails'
gem 'whenever'

# Following are the rails-assets.org gems
gem 'rails-assets-axios', source: 'https://rails-assets.org'
gem 'rails-assets-bootstrap-tagsinput', source: 'https://rails-assets.org'
gem 'rails-assets-jquery-timeago', source: 'https://rails-assets.org'
gem 'rails-assets-jquery-typeahead', source: 'https://rails-assets.org'
gem 'rails-assets-jquery.appear.js', source: 'https://rails-assets.org'
gem 'rails-assets-jquery.dotdotdot', source: 'https://rails-assets.org'
gem 'rails-assets-jsdiff', source: 'https://rails-assets.org'
gem 'rails-assets-typeahead.js', source: 'https://rails-assets.org'
gem 'rails-assets-underscore', source: 'https://rails-assets.org'

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

group :development, :test do
  gem 'capybara'
  gem 'guard-rspec'
  gem 'launchy'
  gem 'poltergeist'
  gem 'pry'
  gem 'rspec-rails'
  gem 'spring'
  gem 'terminal-notifier-guard'
end

group :production do
  gem 'rails_12factor'
end
