// This file shows the mappings from the XML tags generated by the CMS API and
// The Tech's custom paragraph styles in InDesign. The correct InDesign
// paragraph style to use is determined by the section, the primary tag of
// the article (also known as an "article tag"), and the XML tag.
//
// The structure of this object:
// {section: {primary_tag: [[xml_tag, InDesign_paragraph_style]]}}
//
// When trying to find the correct InDesign paragraph style to use, if no match
// is found for an article's primary_tag within its section, or if the article
// has no primary_tag, then the "_default" dictionary is used.
//
// Notes
// -----
//
// The following mappings make use of XML tags that are currently not
// used by the CMS API, but which should ideally be implemented. Production
// must therefore set these manually.
//
// <signature> OPN-LettersSignature
// <event_desc> RTZ-EventDesc Bold
//
// This file does not map anything to the following InDesign paragraph styles.
// Production must set them manually in InDesign.
//
// NUZ-InsideBoxDscrpn
// NUZ-InsideBoxHead
// FTO-PhotoCredit
// FTO-PhotoCaption
// FTO-METAhead
// FTO-BoxPicHead
// OPN-OpinionPolicyHead
// CL-EventsBody
// CL-EventsHead
// CL-EventsDay
// CL-EventsFoot
// SPO-HomeEventsDate
// SPO-HomeEventsSports
// SPO-ScoreboardBody
// SPO-ScoreboardDate
// SPO-ScoreboardScore
// SPO-ScoreboardSport
// SPO-SportsShortsHead
// WN-ExtendedForecast
// WN-ExtendedForecastHead
// WN-ShortsHeadline
// ALL-BylineNoTitle
// ALL-Header
// ALL-Main Quote Txt
// ALL-Quote Attribution Dscrptn
// ALL-Quote Attribution Name
// ALL-SideSectionHeads
//
// The "brief" primary tag was not widely used before 2015. Briefs without the
// "brief" primary tag will not be imported with the correct headline style.
//
// As of January 2015, there is no InDesign paragraph style in our templates
// for bylines in news briefs. For briefs imported from our CMS, the style of
// these bylines must also be set manually by Production.

{
  "News": {
    "_default": [
      ["primary_tag", "ALL-ArticleTag Red"],
      ["headline", "NUZ-Headline"],
      ["subhead", "NUZ-Subhead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "All-Body"],
      ["h2", "NUZ-BodySub"]
    ],
    "brief": [
      ["primary_tag", "ALL-ArticleTag Red"],
      ["headline", "NUZ-Briefhead"],
      ["subhead", "NUZ-Briefhead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "All-Body"],
      ["h2", "NUZ-BodySub"]
    ],
    "in short": [
      ["primary_tag", "ALL-ArticleTag Cyan"],
      ["headline", "NUZ-Headline"],
      ["subhead", "NUZ-Subhead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "NUZ-InShort"],
      ["h2", "NUZ-BodySub"]
    ],
    "weather": [
      ["primary_tag", "ALL-ArticleTag Gray"],
      ["headline", "WN-WeatherHead"],
      ["subhead", "NUZ-Subhead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "All-Body"],
      ["h2", "NUZ-BodySub"]
    ],
  },
  "Opinion": {
    "_default": [
      ["primary_tag", "ALL-ArticleTag Gray"],
      ["headline", "OPN-Headline"],
      ["subhead", "OPN-Subhead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "ALL-Body"],
      ["h2", "OPN-BodySub"]
    ],
    "letters to the editor": [
      ["primary_tag", "ALL-ArticleTag Gray"],
      ["headline", "OPN-LettersHead"],
      ["subhead", "OPN-LettersHead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "OPN-LettersBody"],
      ["h2", "OPN-LettersHead"],
      ["signature", "OPN-LettersSignature"] // <signature> is not currently used
    ],
    "editorial": [
      ["primary_tag", "ALL-ArticleTag Gray"],
      ["headline", "OPN-EditorialHeadline"],
      ["subhead", "OPN-EditorialSubhead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "ALL-Body"],
      ["h2", "OPN-BodySub"]
    ]
  },
  "Arts": {
    "_default": [
      ["primary_tag", "ALL-ArticleTag Red"],
      ["headline", "RTZ-Headline"],
      ["subhead", "RTZ-Subhead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "ALL-Body"],
      ["h2", "RTZ-BodySub"],
      ["event_desc", "RTZ-EventDesc Bold"] // <event_desc> is not currently used
    ]
  },
  "Campus Life": {
    "_default": [
      ["primary_tag", "ALL-ArticleTag Red"],
      ["headline", "CL-Headline"],
      ["subhead", "CL-Subhead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "ALL-Body"],
      ["h2", "CL-BodySub"]
    ],
  },
  "Sports": {
    "_default": [
      ["primary_tag", "ALL-ArticleTag Red"],
      ["headline", "SPO-Headline"],
      ["subhead", "SPO-Subhead"],
      ["byline", "ALL-Byline w/ Title"],
      ["bytitle", "ALL-By Title"],
      ["p", "ALL-Body"],
      ["h2", "SPO-BodySub"]
    ],
  },
}
