# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook 'poise-ruby'
cookbook 'poise-ruby-build'
cookbook 'postgresql'
cookbook 'apt'
cookbook 'redisio'
cookbook 'java', '~> 2.1.0'
cookbook 'elasticsearch', '~> 3.0'
