require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ArticleListsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ArticleList. As you add validations to ArticleList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArticleListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all article_lists as @article_lists" do
      article_list = ArticleList.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:article_lists)).to eq([article_list])
    end
  end

  describe "GET show" do
    it "assigns the requested article_list as @article_list" do
      article_list = ArticleList.create! valid_attributes
      get :show, {:id => article_list.to_param}, valid_session
      expect(assigns(:article_list)).to eq(article_list)
    end
  end

  describe "GET new" do
    it "assigns a new article_list as @article_list" do
      get :new, {}, valid_session
      expect(assigns(:article_list)).to be_a_new(ArticleList)
    end
  end

  describe "GET edit" do
    it "assigns the requested article_list as @article_list" do
      article_list = ArticleList.create! valid_attributes
      get :edit, {:id => article_list.to_param}, valid_session
      expect(assigns(:article_list)).to eq(article_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ArticleList" do
        expect {
          post :create, {:article_list => valid_attributes}, valid_session
        }.to change(ArticleList, :count).by(1)
      end

      it "assigns a newly created article_list as @article_list" do
        post :create, {:article_list => valid_attributes}, valid_session
        expect(assigns(:article_list)).to be_a(ArticleList)
        expect(assigns(:article_list)).to be_persisted
      end

      it "redirects to the created article_list" do
        post :create, {:article_list => valid_attributes}, valid_session
        expect(response).to redirect_to(ArticleList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved article_list as @article_list" do
        post :create, {:article_list => invalid_attributes}, valid_session
        expect(assigns(:article_list)).to be_a_new(ArticleList)
      end

      it "re-renders the 'new' template" do
        post :create, {:article_list => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested article_list" do
        article_list = ArticleList.create! valid_attributes
        put :update, {:id => article_list.to_param, :article_list => new_attributes}, valid_session
        article_list.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested article_list as @article_list" do
        article_list = ArticleList.create! valid_attributes
        put :update, {:id => article_list.to_param, :article_list => valid_attributes}, valid_session
        expect(assigns(:article_list)).to eq(article_list)
      end

      it "redirects to the article_list" do
        article_list = ArticleList.create! valid_attributes
        put :update, {:id => article_list.to_param, :article_list => valid_attributes}, valid_session
        expect(response).to redirect_to(article_list)
      end
    end

    describe "with invalid params" do
      it "assigns the article_list as @article_list" do
        article_list = ArticleList.create! valid_attributes
        put :update, {:id => article_list.to_param, :article_list => invalid_attributes}, valid_session
        expect(assigns(:article_list)).to eq(article_list)
      end

      it "re-renders the 'edit' template" do
        article_list = ArticleList.create! valid_attributes
        put :update, {:id => article_list.to_param, :article_list => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested article_list" do
      article_list = ArticleList.create! valid_attributes
      expect {
        delete :destroy, {:id => article_list.to_param}, valid_session
      }.to change(ArticleList, :count).by(-1)
    end

    it "redirects to the article_lists list" do
      article_list = ArticleList.create! valid_attributes
      delete :destroy, {:id => article_list.to_param}, valid_session
      expect(response).to redirect_to(article_lists_url)
    end
  end

end
